insert into public.site_settings(business_name,slogan,address,opening_hours,whatsapp,whatsapp_message,seo_title,seo_description)
select 'Axis Day Hospital','O seu hospital dia','Avenida Rubem Berta, 850 — Conjunto 1704 — Indianápolis — São Paulo/SP','Segunda a sexta-feira, das 07:00 às 19:00','11945683663','Olá. Gostaria de conhecer o Axis Day Hospital e saber mais sobre o credenciamento.','Axis Day Hospital | Estrutura moderna para médicos em São Paulo','Hospital para procedimentos invasivos de curta permanência em São Paulo, com estrutura moderna para pacientes, médicos e equipes.'
where not exists(select 1 from public.site_settings);

insert into public.page_sections(section_key,eyebrow,title,description,cta_label,cta_url,active,sort_order,content) values
('hero','Day Hospital · São Paulo','O seu hospital dia','Um Day Hospital para procedimentos de curta permanência, onde tecnologia, acolhimento e segurança caminham juntos.','Conheça o Axis','#o-axis',true,10,'{}'),
('positioning','Axis Day Hospital','O cuidado começa antes da cirurgia.','O Axis é especializado em procedimentos invasivos de curta permanência. Cada ambiente foi planejado para oferecer conforto aos pacientes e praticidade às equipes médicas, favorecendo um atendimento organizado, eficiente e humanizado.',null,null,true,20,'{}'),
('experience','Experiência Axis','Uma jornada preparada em cada etapa.','Para pacientes que necessitam de procedimentos cirúrgicos de curta permanência e para médicos que buscam uma estrutura moderna, segura e organizada para realizá-los.',null,null,true,25,'{"items":[{"title":"Antes do procedimento","description":"Espaços que podem receber consultas pré-operatórias, avaliações anestésicas e outros atendimentos relacionados ao procedimento."},{"title":"Após o procedimento","description":"Uma sala de recuperação cuidadosamente monitorizada, com a assistência necessária para uma recuperação segura e confortável."}]}'),
('physicians','De médico para médico','Prontos para cuidar do seu paciente junto com você.','O Axis recebe médicos e suas equipes em uma estrutura organizada para apoiar o procedimento, com espaços planejados para o cuidado e o atendimento aos pacientes.','Fale conosco e faça seu credenciamento','#contato',true,30,'{}'),
('process','Como funciona','Uma conversa clara, do primeiro contato à organização.','Nossa equipe entende a necessidade do médico, apresenta a estrutura e as condições e orienta os primeiros passos do credenciamento.',null,null,true,40,'{"steps":["Fale com o Axis","Conte sua necessidade","Conheça a estrutura e as condições","Inicie seu credenciamento"]}'),
('structure','Conheça o Axis','Estrutura pensada nos detalhes.','Ambientes e salas cirúrgicas preparados com infraestrutura e equipamentos para integrar segurança, tecnologia e acolhimento durante a experiência de médicos, equipes e pacientes.',null,null,true,42,'{}'),
('education','Educação e atualização','Tecnologia a serviço do cuidado e do ensino.','Uma câmera 4K integrada ao foco cirúrgico permite filmar e transmitir procedimentos ao vivo em alta definição. O recurso amplia as possibilidades de aulas, treinamentos e cursos para atualização profissional e troca de conhecimento.',null,null,true,45,'{}'),
('editorial_cta','Próximo passo','Tecnologia que inspira confiança. Cuidado que faz a diferença.','Conheça uma estrutura preparada para receber você, sua equipe e seus pacientes — antes, durante e após o procedimento.','Fale conosco e faça seu credenciamento','#contato',true,50,'{}')
on conflict(section_key) do update set eyebrow=excluded.eyebrow,title=excluded.title,description=excluded.description,content=excluded.content,cta_label=excluded.cta_label,cta_url=excluded.cta_url,active=excluded.active,sort_order=excluded.sort_order,updated_at=now();

insert into public.differentials(title,description,active,sort_order) values
('Segurança','Protocolos assistenciais conduzidos em ambiente licenciado pela Vigilância Sanitária.',true,10),
('Tecnologia','Salas cirúrgicas equipadas e recursos integrados para apoiar o cuidado e a atuação das equipes.',true,20),
('Suporte à equipe médica','Estrutura organizada para receber médicos, equipes e pacientes ao longo do procedimento.',true,30);
