import type{GalleryItem,SiteSettings}from"@/types/database";
export type EquipmentItem={name:string;category:string;description:string};
export const confirmedSettings:SiteSettings={business_name:"Axis Day Hospital",slogan:"O seu hospital dia",phone:null,whatsapp:"11945683663",whatsapp_message:"Olá. Gostaria de conhecer o Axis Day Hospital e saber mais sobre o credenciamento.",email:null,address:"Avenida Rubem Berta, 850 — Conjunto 1704 — Indianápolis — São Paulo/SP",opening_hours:"Segunda a sexta-feira, das 07:00 às 19:00",instagram_url:null,maps_url:"https://www.google.com/maps/dir/?api=1&destination=Avenida%20Rubem%20Berta%2C%20850%2C%20Indian%C3%A1polis%2C%20S%C3%A3o%20Paulo%2C%20SP",maps_embed:"https://www.google.com/maps?q=Avenida%20Rubem%20Berta%2C%20850%2C%20Indian%C3%A1polis%2C%20S%C3%A3o%20Paulo%2C%20SP&output=embed"};
export const gallerySeed:GalleryItem[]=[["RCZ_2199-HDR.jpg","Ambiente cirúrgico do Axis Day Hospital"],["RCZ_2303.jpg","Recepção do Axis Day Hospital"],["RCZ_2285.jpg","Corredor interno do Axis Day Hospital"],["RCZ_2211.jpg","Detalhe de ambiente cirúrgico do Axis Day Hospital"],["RCZ_2318-HDR.jpg","Ambiente de apoio do Axis Day Hospital"],["RCZ_2162.jpg","Ambiente interno do Axis Day Hospital"]].map(([file,alt],i)=>({id:`seed-${i}`,title:"Axis Day Hospital",alt_text:alt,image_url:`/images/${file}`,category:i<2?"Institucional":"Estrutura",sort_order:i,active:true}));
export const equipmentSeed:EquipmentItem[]=[
 {name:"Lipoaspirador Rhosse",category:"Lipoaspiração",description:"Equipamento descrito no material fornecido com potência de 650 mmHg, desenvolvido para apoiar a lipoaspiração com precisão e desempenho."},
 {name:"Retraction",category:"Lipoaspiração e retração da pele",description:"Tecnologia sul-coreana apresentada no material com combinação de lipoaspiração ultrassônica e retração da pele no mesmo equipamento."},
 {name:"Argoplasma",category:"Retração da pele",description:"Tecnologia de plasma com gás argônio descrita para retração e diminuição da flacidez da pele em procedimentos estéticos."},
 {name:"Renuvion",category:"Retração da pele",description:"Combinação de radiofrequência e plasma de gás hélio apresentada para retração da pele e melhora da firmeza do tecido subcutâneo."},
 {name:"Vaser",category:"Lipoaspiração ultrassônica",description:"Equipamento de lipoaspiração ultrassônica que emulsifica a gordura e facilita sua remoção com precisão e suavidade."},
 {name:"BodyTite",category:"Contorno corporal e facial",description:"Tecnologia de radiofrequência para aquecimento e retração dos tecidos, com ponteiras BodyTite, FaceTite, AccuTite e Morpheus mencionadas no material."},
 {name:"Laser CO₂",category:"Cirurgia plástica, dermatologia e ginecologia",description:"Laser de CO₂ com seleção de parâmetros e ponteira de corte, conforme o material fornecido, para procedimentos a laser."},
 {name:"Piezo",category:"Rinoplastia e remodelação óssea",description:"Bisturi ultrassônico descrito para procedimentos de remodelação óssea e rinoplastia, com atuação precisa sobre o osso."},
 {name:"Vibrolipo",category:"Lipoaspiração",description:"Dispositivo de vibração para a cânula de lipoaspiração, apresentado para otimizar a remoção da gordura e reduzir o esforço do cirurgião."},
];
