import type{GalleryItem,SiteSettings}from"@/types/database";
export type EquipmentItem={name:string;category:string;description:string;image:string;source:string};
export const confirmedSettings:SiteSettings={business_name:"Axis Day Hospital",slogan:"O seu hospital dia",phone:null,whatsapp:"11945683663",whatsapp_message:"Olá. Gostaria de conhecer o Axis Day Hospital e saber mais sobre o credenciamento.",email:null,address:"Avenida Rubem Berta, 850 — Conjunto 1704 — Indianápolis — São Paulo/SP",opening_hours:"Segunda a sexta-feira, das 07:00 às 19:00",instagram_url:null,maps_url:"https://www.google.com/maps/dir/?api=1&destination=Avenida%20Rubem%20Berta%2C%20850%2C%20Indian%C3%A1polis%2C%20S%C3%A3o%20Paulo%2C%20SP",maps_embed:"https://www.google.com/maps?q=Avenida%20Rubem%20Berta%2C%20850%2C%20Indian%C3%A1polis%2C%20S%C3%A3o%20Paulo%2C%20SP&output=embed"};
export const gallerySeed:GalleryItem[]=[["RCZ_2199-HDR.jpg","Ambiente cirúrgico do Axis Day Hospital"],["RCZ_2303.jpg","Recepção do Axis Day Hospital"],["RCZ_2285.jpg","Corredor interno do Axis Day Hospital"],["RCZ_2211.jpg","Detalhe de ambiente cirúrgico do Axis Day Hospital"],["RCZ_2318-HDR.jpg","Ambiente de apoio do Axis Day Hospital"],["RCZ_2162.jpg","Ambiente interno do Axis Day Hospital"]].map(([file,alt],i)=>({id:`seed-${i}`,title:"Axis Day Hospital",alt_text:alt,image_url:`/images/${file}`,category:i<2?"Institucional":"Estrutura",sort_order:i,active:true}));
export const equipmentSeed:EquipmentItem[]=[
 {name:"Lipoaspirador Rhosse",category:"Lipoaspiração",description:"Equipamento de aspiração para procedimentos de lipoaspiração; a imagem é representativa da linha Rhosse.",image:"https://api.techealth.com.br/img/produto/959_6275c14f2309e.png",source:"TecHealth — Jumas LIPO-RHOSSE"},
 {name:"Retraction",category:"Lipoaspiração e retração da pele",description:"Sistema de radiofrequência apresentado para apoiar a retração da pele e a emulsificação da gordura durante procedimentos de lipoaspiração.",image:"https://www.drfredericofernandes.com.br/wp-content/uploads/2024/01/Dr-Frederico-Fernandes-Dica-2024-01-26-Retraction.jpg",source:"Tentrek Lasers (imagem publicada por clínica)"},
 {name:"Argoplasma",category:"Retração da pele",description:"Tecnologia de plasma com gás argônio apresentada para retração e diminuição da flacidez da pele.",image:"https://vibrofit.com.br/imagens/produtos/destaques/faga_argoplasma.jpg",source:"FAGA Medical"},
 {name:"Renuvion",category:"Retração da pele",description:"Sistema que combina radiofrequência e plasma de gás hélio para retração da pele, conforme a descrição do material.",image:"https://www.datocms-assets.com/120171/1713296689-machine.webp",source:"Apyx Medical (imagem publicada por clínica)"},
 {name:"Vaser",category:"Lipoaspiração ultrassônica",description:"Equipamento de lipoaspiração ultrassônica que emulsifica a gordura e facilita sua remoção com precisão.",image:"https://suckhoe123.vn/uploads/lam-dep/hut-mo-vaser.jpg",source:"VASERlipo (imagem representativa)"},
 {name:"Torre de Videocirurgia Stryker 1688 AIM 4K",category:"Videocirurgia",description:"Torre de videocirurgia disponível para locação, com resolução 4K nativa, definição de imagem, reprodução precisa de cores e iluminação otimizada para visualização detalhada durante os procedimentos.",image:"/images/torre-videocirurgia-stryker-1688-aim-4k.jpg",source:"Imagem fornecida pelo Axis Day Hospital"},
 {name:"BodyTite",category:"Contorno corporal e facial",description:"Tecnologia de radiofrequência para aquecimento e retração dos tecidos, com ponteiras BodyTite, FaceTite, AccuTite e Morpheus.",image:"https://images.dotmed.com/images/listingpics2/5/5/2/6/5526347_2.jpg",source:"InMode BodyTite (imagem representativa)"},
 {name:"Laser CO₂",category:"Cirurgia plástica, dermatologia e ginecologia",description:"Laser de CO₂ com seleção de parâmetros e ponteira de corte, conforme o material fornecido.",image:"https://i0.wp.com/www.laksamanakarya.com/wp-content/uploads/2021/05/Deka-SmartXide-Fractional-Co2-1.jpg?fit=500%2C500&ssl=1",source:"DEKA SmartXide (imagem representativa)"},
 {name:"Piezo",category:"Rinoplastia e remodelação óssea",description:"Bisturi ultrassônico descrito para procedimentos de remodelação óssea e rinoplastia.",image:"https://www.datocms-assets.com/61140/1644943270-piezotome.jpg?auto=format",source:"Acteon Piezotome (imagem representativa)"},
 {name:"Vibrolipo",category:"Lipoaspiração",description:"Dispositivo de vibração para a cânula de lipoaspiração, apresentado para otimizar a remoção da gordura.",image:"https://fagamed.com.br/wp-content/uploads/2025/06/faga_vibrofit.jpg",source:"FAGA Medical — Vibrofit"},
];
